import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/ui/header";
import { Navbar } from "@/components/ui/navbar";
import AppProvider from "./provider";
import ContentLayout from "@/components/layouts/content-layout";

const fontInter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Íris",
  //description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontInter.variable} antialiased flex flex-col gap-22`}
      >
        <AppProvider>
          <ContentLayout>
            {children}
          </ContentLayout>
        </AppProvider>
      </body>
    </html>
  );
}
